layout_spectrum: 0.4297872
typography_spectrum: 0.4191489
color:
  lightness: 0
  brandStrength: 0.666055
  saturation: 1
  rhythmicContrast: 0.5915265
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Anderson Cutlery
